### ISSUE TITLE
Non-generic Emit is needed

### ISSUE THREAD

**Issue by masonwheeler** [kevin-montrose/Sigil#32]
When I ran across Sigil, I immediately thought, "this is exactly what I need."  I'm working on a compiler that uses `Reflection.Emit` for code generation, and there's one case that's producing code that doesn't verify, for reasons that no one seems to be able to track down.  Having Sigil available to provide verification as it goes would be amazing.

Unfortunately, the current API is completely unsuitable for this task, because it requires all methods to have a known delegate type.  There are three serious problems with this.

1. It's possible to use reflection to create an arbitrary generic delegate type at runtime, and invoke a method based on that, but this would involve *massive* code duplication for generating functions of different arity.
2. Would the trick from 1) even work for a type that still only exists as a `TypeBuilder`?
3. Some functions, such as constructors, simply can't be made into a delegate.

Because of these problems, a non-generic Emit is really necessary before Sigil can be used for its advertised purpose as "a roughly 1-to-1 replacement for ILGenerator."

**Comment by Wazner** [comment]
I don't think you've looked good enough, Sigil does support non-generic emit. Just check out the [NonGeneric](https://github.com/kevin-montrose/Sigil/tree/a8fbd7c849102c34836c9428ee9f9d324de53515/Sigil/NonGeneric) folder in the repository.

Sigil supports building constructors using the [`Emit<DelegateType>.BuildConstructor`](https://github.com/kevin-montrose/Sigil/blob/a8fbd7c849102c34836c9428ee9f9d324de53515/Sigil/Emit.cs#L780) and [`NonGeneric.Emit.BuildConstructor`](https://github.com/kevin-montrose/Sigil/blob/a8fbd7c849102c34836c9428ee9f9d324de53515/Sigil/NonGeneric/Emit.cs#L399).

**Comment by masonwheeler** [comment]
Oh!  No, I totally overlooked that.  Thanks!
