### ISSUE TITLE
Support for Net Standard 2.0

### ISSUE THREAD

**Issue by ben-foster-cko** [kevin-montrose/Sigil#58]
Do you have plans to support Net Standard 2.0? Since upgrading one of our projects to .NET Core 2.0, our builds are failing and it appears the issue is that we're using JIL that depends on Sigil which has dependencies on RC packages:

> [09:05:37][Step 1/1] C:\Program Files\dotnet\sdk\2.0.0\NuGet.targets(102,5): error : Could not find file 'C:\Windows\system32\config\systemprofile\.nuget\packages\system.diagnostics.debug\4.0.11-rc2-24027\system.diagnostics.debug.nuspec'. [D:\TeamCity\buildAgent2\work\build\src\Gateway.Api\Gateway.Api.csproj]

**Comment by nothrow** [comment]
I've added support for net core 2.0, and created pull request, but since the project looks dead, here is newer nuget: https://www.nuget.org/packages/Sigil.NetStandard/4.8.0
source:
https://github.com/nothrow/Sigil

**Comment by Konard** [comment]
@nothrow why have you deleted your fork for 4.8.0 version? Looks like it is better to make a pull request.

**Comment by Konard** [comment]
@kevin-montrose accept pull request for .NET Standard 2.0 support, please. I have a ton of packages depending on it. And just cannot drop dependency.

**Comment by Konard** [comment]
The other way to get support for .NET Standard is to use fork supported by my organization: https://github.com/linksplatform/Sigil

**Comment by NickCraver** [comment]
This was completed in the 5.0.0 release which is not `net461`, `netstandard2.0`, and `netstandard2.1` (which requires no dependencies). /cc @kevin-montrose

**Comment by NickCraver** [comment]
Closing this out since it's live on NuGet now :)
